### PR TITLE
Cleanup (Broken, 17 errors of LNK2019: unresolved external symbols)

### PR DESCRIPTION
**Pull request by Jrgamer4u**
same as #1 but renaming the branch deleted it ig 💢 
idk what i'm doing still

#3 replaces this, which adds the changes from non-vlc folder.

### CODE REVIEW

**Comment by DotWith** [comment]
I didn't see this pr.
I tested I had the same issues with it not compiling the cpp. Maybe you can fix it? `¯\_(ツ)_/¯`

**Comment by Jrgamer4u** [comment]
i have completely forgot about this and don't know how to fix my own code bc my brain is currently rotting :)
ill probably make it messier if i tried anyway

**Comment by Jrgamer4u** [comment]
eh

**Comment by Jrgamer4u** [comment]
i have no idea what broke it

it always spews this now

something to do with a "VlcBitmap.obj" and "LibVLC"


```
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: static class LibVLC * __cdecl LibVLC::create(void)" (?create@LibVLC@@SAPEAV1@XZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objcreate(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objcreate@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::play(void)" (?play@LibVLC@@QEAAXXZ) referenced in function "public: virtual void __cdecl hxcodec::cpp::VlcBitmap_obj::play(class String)" (?play@VlcBitmap_obj@cpp@hxcodec@@UEAAXVString@@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::play(char const *)" (?play@LibVLC@@QEAAXPEBD@Z) referenced in function "public: virtual void __cdecl hxcodec::cpp::VlcBitmap_obj::play(class String)" (?play@VlcBitmap_obj@cpp@hxcodec@@UEAAXVString@@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::stop(void)" (?stop@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objdispose(class hx::Object *)" (?__VlcBitmap_objdispose@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::pause(void)" (?pause@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objonFocusLost(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objonFocusLost@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::resume(void)" (?resume@LibVLC@@QEAAXXZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objonFocus(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objonFocus@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: __int64 __cdecl LibVLC::getLength(void)" (?getLength@LibVLC@@QEAA_JXZ) referenced in function "public: void __cdecl hxcodec::cpp::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@cpp@hxcodec@@QEAAXXZ)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: __int64 __cdecl LibVLC::getDuration(void)" (?getDuration@LibVLC@@QEAA_JXZ) referenced in function "public: void __cdecl hxcodec::cpp::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@cpp@hxcodec@@QEAAXXZ)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: int __cdecl LibVLC::getWidth(void)" (?getWidth@LibVLC@@QEAAHXZ) referenced in function "public: void __cdecl hxcodec::cpp::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@cpp@hxcodec@@QEAAXXZ)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: int __cdecl LibVLC::getHeight(void)" (?getHeight@LibVLC@@QEAAHXZ) referenced in function "public: void __cdecl hxcodec::cpp::VlcBitmap_obj::videoInitComplete(void)" (?videoInitComplete@VlcBitmap_obj@cpp@hxcodec@@QEAAXXZ)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: unsigned char * __cdecl LibVLC::getPixelData(void)" (?getPixelData@LibVLC@@QEAAPEAEXZ) referenced in function "public: void __cdecl hxcodec::cpp::VlcBitmap_obj::render(void)" (?render@VlcBitmap_obj@cpp@hxcodec@@QEAAXXZ)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::setVolume(float)" (?setVolume@LibVLC@@QEAAXM@Z) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objsetVolume(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objsetVolume@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: float __cdecl LibVLC::getVolume(void)" (?getVolume@LibVLC@@QEAAMXZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objgetVolume(class hx::Object *)" (?__VlcBitmap_objgetVolume@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: __int64 __cdecl LibVLC::getTime(void)" (?getTime@LibVLC@@QEAA_JXZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objgetTime(class hx::Object *)" (?__VlcBitmap_objgetTime@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::setPosition(float)" (?setPosition@LibVLC@@QEAAXM@Z) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objseek(class hx::Object *,class Dynamic const &)" (?__VlcBitmap_objseek@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@AEBV3@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: float __cdecl LibVLC::getFPS(void)" (?getFPS@LibVLC@@QEAAMXZ) referenced in function "class Dynamic __cdecl hxcodec::cpp::__VlcBitmap_objgetFPS(class hx::Object *)" (?__VlcBitmap_objgetFPS@cpp@hxcodec@@YA?AVDynamic@@PEAVObject@hx@@@Z)
c2e389ff_VlcBitmap.obj : error LNK2019: unresolved external symbol "public: void __cdecl LibVLC::setRepeat(int)" (?setRepeat@LibVLC@@QEAAXH@Z) referenced in function "public: virtual void __cdecl hxcodec::cpp::VlcBitmap_obj::play(class String)" (?play@VlcBitmap_obj@cpp@hxcodec@@UEAAXVString@@@Z)
ApplicationMain.exe : fatal error LNK1120: 17 unresolved externals
```

**Comment by Jrgamer4u** [comment]
> I didn't see this pr. I tested I had the same issues with it not compiling the cpp. Maybe you can fix it? `¯\_(ツ)_/¯`

i cant, i have no idea what caused it, most of the changes is formatting the vlc folder anyways, you can just reformat the vlc folder and 90% of the changes will be redundant.

**Comment by DotWith** [comment]
okie dokkie 👌

**Comment by Jrgamer4u** [comment]
@DotWith (sorry for ping) #3 is created so I'm closing this
my brain is the most inconsistent thing in the world

**Pull request closed without merging**
